### PR TITLE
fix content download for private repo

### LINKED ISSUE #215: [BUG] reports from git history don't work for private repo
## issue

when running `go run openapi-changes.go html-report` on a private repo with the GH_TOKEN set as env variable, a 404 is returned.

Image

This is likely cause in `github.go` we try to download the file using a raw url from the commit response
```go
r, _ = http.NewRequest(http.MethodGet, commit.Files[x].RawURL, nil)
```

## Possible Solution

use [Content API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content) to get a download url with authentication token, we can then download the content from the retuned url

### PR DESCRIPTION
**Pull request by FedeBev**
Fix #215

### CODE REVIEW

File: cmd/html_report.go [hunk 1]
```diff
@@ -276,8 +276,8 @@ func GetHTMLReportCommand() *cobra.Command {
 	return cmd
 }
 
-func writeReportFile(err error, reportFile string, report []byte) error {
-	err = os.WriteFile(reportFile, report, 0744)
+func writeReportFile(reportFile string, report []byte) error {
```
Comment (FedeBev) [inline cmd/html_report.go:279]: fix for `fix argument err is overwritten before first use`
